name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.0
  - python=3.9.1
  - pip:
    - fastapi==0.63.0
    - flask==1.1.2
    - jupyterhub==1.3.0
    - requests==2.25.1
    - typer==0.3.2
    - uvicorn==0.13.3
    