version: '2.1'
services:
  cdsdashboards:
    build:
      context: ../
      dockerfile: ${JH_CYPRESS_DOCKERFILE:-Dockerfile}
      args:
        BASE_IMAGE: ${JH_CYPRESS_BASE_IMAGE}
    environment:
      - JH_CYPRESS_JHCONFIG_SRC=${JH_CYPRESS_JHCONFIG_SRC}
      - JH_CYPRESS_JHCONFIG_DEST=${JH_CYPRESS_JHCONFIG_DEST}
      - JH_CYPRESS_SQLITE_SRC=${JH_CYPRESS_SQLITE_SRC}
      - JH_CYPRESS_SQLITE_DEST=${JH_CYPRESS_SQLITE_DEST}
      - JH_CYPRESS_HOME_SRC=${JH_CYPRESS_HOME_SRC}
      - JH_CYPRESS_HOME_DEST=${JH_CYPRESS_HOME_DEST}
      - JH_CYPRESS_CREATE_USERS=${JH_CYPRESS_CREATE_USERS}
    volumes:
      - ./jupyterhub_config:/jh_cypress_config
    labels:
      - "com.containds.e2etest=container"
    ports:
      - 16000:80
    privileged: true

  cypress:
    image: "cypress/included:4.4.0"
    depends_on:
      - cdsdashboards
    command: ["--spec", "${JH_CYPRESS_TESTS}", "--config", "videosFolder=cypress/videos/${JH_CYPRESS_MEDIAFOLDER:-any},screenshotsFolder=cypress/screenshots/${JH_CYPRESS_MEDIAFOLDER:-any}"]
    environment:
      - CYPRESS_baseUrl=http://cdsdashboards:80
    working_dir: /e2e
    volumes:
      - ./:/e2e
