name: z2jh Docker image from local repo

on:
  push:
    branches:
      - '**'

jobs:
  
  build_cdsdashboards_local:
    name: Build and Push cdsdashboards-jupyter-k8s-hub local
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build docker 
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./
          dockerfile: ./docker-images/z2jh/hub/Dockerfile
          repository: ideonate/cdsdashboards-jupyter-k8s-hub
          tag_with_ref: false
          tag_with_sha: true
          